service: aws-videojuego
frameworkVersion: '2 || 3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:us-east-1:668643299204:table/VideojuegoTable"

resources:
  Resources:
    VideojuegoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: VideojuegoTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  crearVideojuego:
    handler: src/handlers/crearVideojuego.handler
    events:
      - httpApi:
          path: /videojuego
          method: POST
  listarVideojuego:
    handler: src/handlers/listarVideojuegos.handler
    events:
      - httpApi:
          path: /videojuegos
          method: GET
  actualizarVideojuego:
    handler: src/handlers/actualizarVideojuego.handler
    events:
      - httpApi:
          path: /UpdatedVideojuego/{id}
          method: PUT
  obtenerVideojuego:
    handler: src/handlers/obtenerVideojuego.handler
    events:
      - httpApi:
          path: /videojuego/{id}
          method: GET
  eliminarVideojuego:
    handler: src/handlers/eliminarVideojuego.handler
    events:
      - httpApi:
          path: /eliminarVideojuego/{id}
          method: DELETE
  
  


custom:
  bundle:
    linting: false